package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/IGassmann/graphql-playground/apps/api/graph/model"
)

// AllStarships is the resolver for the allStarships field.
func (r *queryResolver) AllStarships(ctx context.Context, after *string, first *int, before *string, last *int) (*model.StarshipsConnection, error) {
	panic(fmt.Errorf("not implemented: AllStarships - allStarships"))
}

// Starship is the resolver for the starship field.
func (r *queryResolver) Starship(ctx context.Context, id *string) (*model.Starship, error) {
	panic(fmt.Errorf("not implemented: Starship - starship"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
